import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { runIndependentVerification } from '../../src/server/services/dataenrichment/verifiers/IndependentVerifier';
import { hashCanonicalDataset } from '../../src/server/services/dataenrichment/CanonicalObservationSerializer';
import { CanonicalMarketObservation } from '../../src/server/services/dataenrichment/DataStagingContract';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';

describe('IndependentVerifier', () => {
  let tmpDir: string;
  
  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'verifier-test-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('passes a fully valid dataset', () => {
    const rows = [
      {
        securityId: 'NIFTY_50',
        exchange: 'NSE',
        segment: 'EQ',
        timeframe: '15m',
        barStartTime: '2026-09-19T10:15:00+05:30',
        barEndTime: '2026-09-19T10:30:00+05:30',
        open: 100,
        high: 105,
        low: 95,
        close: 102,
        volume: 1000,
        providerTimestamp: '2026-09-19T10:15:00+05:30',
        observationTimestamp: '2026-09-19T10:30:00+05:30',
        dataAcquisitionTimestamp: '2026-09-19T10:35:00+05:30',
        source: 'UPSTOX_V3',
        datasetId: 'TEST_DATASET',
        candleState: 'CLOSED'
      }
    ];

    const dataPath = path.join(tmpDir, 'data.jsonl');
    fs.writeFileSync(dataPath, rows.map(r => JSON.stringify(r)).join('\n') + '\n', 'utf8');

    // Expected canonical string generated by CanonicalObservationSerializer 
    // we'll just mock the hash of exactly what we wrote if this is a naive test,
    // but the verifier runs hashCanonicalDataset. Let's just grab what it would be:
    const canonicalSha256 = hashCanonicalDataset(rows as any);

    const manifest = {
      datasetId: 'TEST_DATASET',
      rawSha256: 'xyz',
      canonicalSha256,
      pitStatus: 'PIT_VERIFIED',
      source: 'UPSTOX_V3',
      provider: 'UPSTOX',
      requestedStart: '2026-09-19T10:15:00+05:30',
      requestedEnd: '2026-09-19T10:30:00+05:30',
      actualStart: '2026-09-19T10:15:00+05:30',
      actualEnd: '2026-09-19T10:30:00+05:30',
      missingRanges: [],
      coverageStart: '2026-09-19T10:15:00+05:30'
    };
    
    const manifestPath = path.join(tmpDir, 'manifest.json');
    fs.writeFileSync(manifestPath, JSON.stringify(manifest), 'utf8');
    
    const rawPath = path.join(tmpDir, 'raw.bin');
    fs.writeFileSync(rawPath, Buffer.from('dummy'));
    const rawSha256 = crypto.createHash('sha256').update(Buffer.from('dummy')).digest('hex');
    manifest.rawSha256 = rawSha256;
    fs.writeFileSync(manifestPath, JSON.stringify(manifest), 'utf8');

    const checks = runIndependentVerification('TEST_DATASET', manifestPath, dataPath, rawPath);
    expect(checks.find(c => c.id === 'schemaValid')?.status).toBe('PASS');
    expect(checks.find(c => c.id === 'noNaN')?.status).toBe('PASS');
    expect(checks.find(c => c.id === 'ohlcRelationshipValid')?.status).toBe('PASS');
    expect(checks.find(c => c.id === 'timestampValid')?.status).toBe('PASS');
  });
});
