import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const dir=path.join(root,'outputs/fundamental_dossiers/pilot_25');
const base=fs.readFileSync(path.join(dir,'Institutional_Due_Diligence_AZAD_RRKABEL.md'),'utf8');
const ref=[
['Immediate catalyst & sentiment','Tier-1 aerospace/defence contract wins and capacity rollout; stated order-book visibility above INR 4,500–5,000 Cr.','Infrastructure and real-estate capex recovery, raw-material pass-through, housing-wire volume recovery and FMEG improvement.'],
['Core product utility','Precision rotating components—airfoils, turbine blades, nozzle guide vanes and rotor assemblies—for aerospace and power turbines.','Building wires, power/specialty cables and FMEG products including fans, switches and lighting.'],
['Strengths & moat','Long qualification cycles, specialist metallurgy and high process-tolerance requirements create a technical switching barrier.','Electrician-network brand, pan-India distribution, product certifications and export approvals.'],
['Customer concentration risk','Reference assessment describes high concentration among major OEM customers; exact percentage requires filing verification.','Reference assessment describes granular retail/B2B demand and low single-customer concentration; filing verification required.'],
['Supplier power and pricing','Specialised alloy supply and indexed pass-through are cited; contract terms require source verification.','Copper/aluminium exposure with distributor price revisions; pass-through evidence requires source verification.'],
['TAM and runway','Reference assessment cites a large global outsourced precision-machining market and low wallet share; market-study source required.','Reference assessment cites a large domestic wires/cables market and organised-sector conversion; market-study source required.'],
['Reinvestment runway','Greenfield capacity dedicated to long-term Tier-1 programmes is cited; order-book and capex documents must corroborate.','Brownfield cabling, warehousing and FMEG investment are cited; capex allocation evidence must corroborate.'],
['Capital allocation efficiency','Front-loaded capex may depress near-term turns; app ROCE is shown separately below.','Asset-turn model and FMEG gestation are cited; app ROCE is shown separately below.'],
['Revenue quality and segments','Reference mix is approximately Energy/Turbines 50%, Aerospace/Defence 45%, balance Oil & Gas; source verification required.','Reference mix is approximately Wires/Cables 88% and FMEG 12%; source verification required.'],
['Margin trajectory','Reference cites EBITDA margins around 34–37%; app statutory operating-profit evidence is shown separately.','Reference cites consolidated EBITDA around 6.5–8.5%; app statutory operating-profit evidence is shown separately.'],
['Cash flow integrity','Reference highlights working-capital absorption from inventory and inspection milestones; app CFO/PAT evidence supports monitoring.','Reference describes stronger cash generation and 75–85% CFO/PAT conversion; app CFO/PAT evidence is shown separately.'],
['Balance sheet and leverage','Reference cites post-IPO net debt/EBITDA below 0.6x; app debt/equity and interest cover are the verified local measures.','Reference cites net debt/EBITDA below 0.5x and strong interest cover; app debt/equity and interest cover are the verified local measures.'],
['Governance and audit','Promoter, strategic backing and audit claims require annual-report confirmation.','Promoter family, professional management and auditor claims require annual-report confirmation.'],
['Structural risks','Customer concentration, qualification delays, delivery lead times and FX exposure are reference watchpoints; verify against filings.','Copper/aluminium volatility, channel inventory, FMEG margin drag and competitive discounting are reference watchpoints; verify against filings.'],
['Valuation and mandate','Reference positions AZAD as aggressive growth/specialty manufacturing; its P/E range conflicts with the app snapshot and must be reconciled by date/provider.','Reference positions RRKABEL as a core industrial compounder; its peer P/E range must be reconciled with the app snapshot by date/provider.']
];
const esc=s=>String(s).replace(/\|/g,'\\|');
const md=['','## Combined interpretation of the supplied institutional reference','', 'The following narrative is the business-language reference supplied for this review. It is dovetailed with the app’s canonical quantitative facts above. Narrative claims remain **reference-sourced and pending independent filing verification**; they are not silently promoted to canonical facts.', '', '| Topic | AZAD — supplied institutional narrative | RRKABEL — supplied institutional narrative |', '|---|---|---|', ...ref.map(r=>`| **${esc(r[0])}** | ${esc(r[1])} | ${esc(r[2])} |`), '', '## Reconciliation and conclusion','', 'AZAD combines strong specialist-manufacturing optionality with currently weak cash conversion in the app snapshot. The supplied narrative supports an aggressive-growth interpretation, but order-book, customer concentration, margin and valuation claims must be tied to dated filings before they can drive a portfolio decision.','', 'RRKABEL combines stronger current cash conversion, low debt/equity and higher ROCE in the app snapshot with a distribution-led electricals narrative. The supplied narrative supports a core-industrial interpretation, but segment mix, peer valuation and FMEG trajectory require dated filings for confirmation.','', '**Decision discipline:** use the app’s canonical figures for quantitative decisions; use the supplied narrative as a research hypothesis until its source documents are persisted and verified.'];
const referencePath=path.join(root,'docs/fundamental/user_supplied_azad_rrkabel_institutional_reference.md');
const reference=fs.readFileSync(referencePath,'utf8');
const out=path.join(dir,'Combined_Institutional_Due_Diligence_AZAD_RRKABEL.md');
fs.writeFileSync(out,base+'\n'+md.join('\n')+'\n\n---\n\n'+reference); console.log(out);
