import fs from 'node:fs';
import path from 'node:path';
import Database from 'better-sqlite3';
import ExcelJS from 'exceljs';

const root = process.cwd();
const symbols = JSON.parse(fs.readFileSync(path.join(root,'data/fundamental_enrichment/pilot_25_manifest.json'),'utf8')).symbols;
const db = new Database(path.join(root,'portfolio.db'), {readonly:true});
const out = path.join(root,'outputs/fundamental_dossiers/pilot_25'); fs.mkdirSync(out,{recursive:true});
const snap = db.prepare(`SELECT analysisType,content,generatedAt FROM dossier_analysis_snapshots WHERE symbol=? ORDER BY generatedAt DESC`);
const raw = db.prepare(`SELECT endpoint,response_json,fetched_at FROM fundamental_endpoint_snapshots WHERE provider='TRENDLYNE_MCP' AND symbol=? ORDER BY fetched_at DESC`);
function parse(v){try{return JSON.parse(v)}catch{return null}}
function latestSections(symbol){const m=new Map(); for(const r of snap.all(symbol)){if(!m.has(r.analysisType))m.set(r.analysisType,{data:parse(r.content),generatedAt:r.generatedAt})} return m}
function compact(v){if(v==null)return 'DATA_INSUFFICIENT'; if(typeof v==='string')return v; if(typeof v==='number')return String(v); if(Array.isArray(v))return v.map(compact).join('; '); if(typeof v==='object'){if('value' in v)return `${v.value==null?'DATA_INSUFFICIENT':v.value} [${v.status||'UNSPECIFIED'}]`; return Object.entries(v).map(([k,x])=>`${k}: ${compact(x)}`).join('; ')} return String(v)}
function sectionText(data){if(!data)return 'DATA_INSUFFICIENT — no persisted analysis snapshot is available for this section.'; return compact(data)}
function build(symbol){const s=latestSections(symbol); const rawRows=raw.all(symbol); const overview=rawRows.find(x=>x.endpoint==='overview'); const events=rawRows.find(x=>x.endpoint==='corporate_events'); const docs=rawRows.find(x=>x.endpoint==='documents'); const exec=s.get('FUNDAMENTAL_EXECUTIVE_SUMMARY')?.data?.summaryText;
 const summary=exec||`${symbol} has persisted provider evidence but no completed executive-analysis snapshot. Fundamental interpretation remains DATA_INSUFFICIENT until the canonical analysis run is completed. Review the detailed evidence, periods, provenance and missing-data checklist before making a decision.`;
 return {symbol,summary,sections:{'Company & Business Model':overview?'Provider overview evidence is available; detailed business-model interpretation requires the persisted analysis snapshot.':'DATA_INSUFFICIENT','Executive Fundamental Summary':summary,'Detailed Fundamentals':sectionText(s.get('FUNDAMENTAL')?.data),'Cash Flow, Balance Sheet & Valuation':sectionText(s.get('FUNDAMENTAL')?.data?.cashFlow||s.get('FUNDAMENTAL')?.data?.valuation),'QGLP':sectionText(s.get('QGLP')?.data),'Technical Context':sectionText(s.get('TECHNICAL')?.data),'Sector & Momentum':sectionText(s.get('SECTOR')?.data),'Risk Management':sectionText(s.get('RISK')?.data),'Catalysts, Risks & Contradictions':events?'Corporate-event evidence is available in the persisted Trendlyne snapshot; interpret event materiality from the source evidence.':'DATA_INSUFFICIENT','Filings & Evidence':docs?'Document-search evidence is available and retained with fetchedAt/source provenance.':'DATA_INSUFFICIENT','Data Gaps & Decision Status':sectionText(s.get('RISK')?.data?.missingData||s.get('FUNDAMENTAL')?.data?.missingDataChecklist||'DATA_INSUFFICIENT')},snapshotCount:s.size,rawEndpointCount:new Set(rawRows.map(x=>x.endpoint)).size};}
const rows=symbols.map(build);
const md=['# WealthOS — Full Fundamental Analysis Template (25 Stocks)','',`Generated ${new Date().toISOString()}. Every section is evidence-bounded. DATA_INSUFFICIENT means the required persisted source or analysis snapshot is absent; no synthetic score or recommendation is created.`,''];
for(const r of rows){md.push(`## ${r.symbol}\n\n### 1. Executive Summary (100–150 words)\n${r.summary}\n`); for(const [k,v] of Object.entries(r.sections))md.push(`### ${k}\n${v}\n`); md.push('---\n');}
fs.writeFileSync(path.join(out,'Full_Fundamental_Analysis_25.md'),md.join('\n'));
fs.writeFileSync(path.join(out,'Full_Fundamental_Analysis_25_data.json'),JSON.stringify({generatedAt:new Date().toISOString(),rows},null,2));
const wb=new ExcelJS.Workbook(); const ws=wb.addWorksheet('Full Analysis'); ws.columns=[{header:'Symbol',key:'symbol',width:16},{header:'Executive Summary',key:'summary',width:100},{header:'Company & Business Model',key:'biz',width:55},{header:'Detailed Fundamentals',key:'fund',width:65},{header:'QGLP',key:'qglp',width:55},{header:'Technical Context',key:'tech',width:55},{header:'Risk Management',key:'risk',width:55},{header:'Data Gaps & Decision Status',key:'gaps',width:55}]; for(const r of rows)ws.addRow({symbol:r.symbol,summary:r.summary,biz:r.sections['Company & Business Model'],fund:r.sections['Detailed Fundamentals'],qglp:r.sections.QGLP,tech:r.sections['Technical Context'],risk:r.sections['Risk Management'],gaps:r.sections['Data Gaps & Decision Status']}); ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}}; ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F766E'}}; for(let i=2;i<=ws.rowCount;i++)for(let j=2;j<=8;j++)ws.getRow(i).getCell(j).alignment={wrapText:true,vertical:'top'}; ws.views=[{state:'frozen',ySplit:1}]; ws.autoFilter='A1:H26';
const one=wb.addWorksheet('One Page Summary'); one.columns=[{header:'Symbol',key:'symbol',width:14},{header:'Executive Summary (100–150 words)',key:'summary',width:105},{header:'Business / Financial View',key:'view',width:70},{header:'QGLP / Technical / Risk',key:'risk',width:70},{header:'Evidence State',key:'state',width:22},{header:'Key Gaps / What to Watch',key:'watch',width:65}]; for(const r of rows){const state=(r.summary.includes('DATA_INSUFFICIENT')||r.sections.QGLP.includes('DATA_INSUFFICIENT'))?'MISSING/CONFLICTING':'MIXED-WATCH'; one.addRow({symbol:r.symbol,summary:r.summary,view:`Business model: ${r.sections['Company & Business Model']}\nFundamentals: ${r.sections['Detailed Fundamentals']}`,risk:`QGLP: ${r.sections.QGLP}\nTechnical: ${r.sections['Technical Context']}\nRisk: ${r.sections['Risk Management']}`,state,watch:r.sections['Data Gaps & Decision Status']});} one.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'},size:12}; one.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1F4E78'}}; for(let i=2;i<=one.rowCount;i++){one.getRow(i).height=130; for(let j=2;j<=6;j++)one.getRow(i).getCell(j).alignment={wrapText:true,vertical:'top'};} one.views=[{state:'frozen',ySplit:1}]; one.autoFilter='A1:F26'; await wb.xlsx.writeFile(path.join(out,'Full_Fundamental_Analysis_25.xlsx'));
console.log(JSON.stringify({symbols:rows.length,withPersistedSnapshots:rows.filter(r=>r.snapshotCount>0).length,markdown:path.join(out,'Full_Fundamental_Analysis_25.md'),workbook:path.join(out,'Full_Fundamental_Analysis_25.xlsx')},null,2)); db.close();
