import fs from 'node:fs'; import path from 'node:path';
const root=process.cwd(), base=JSON.parse(fs.readFileSync(path.join(root,'reports','fundamental-review','NINE_STOCK_DECISION_READY_2026-10-07.json'),'utf8'));
const story={
VMART:{business:'Value-fashion retailer serving mass and aspirational consumers through a store-led format.',growth:'Growth depends on store productivity, like-for-like sales, private-label mix and disciplined expansion.',longevity:'The format can compound if inventory turns and margins remain controlled; retail execution and working capital are the key durability tests.',risks:'Fashion inventory markdowns, weak same-store sales, regional competition and margin pressure.',catalyst:'Sustained same-store growth, improving margins and profitable store additions.'},
RADICO:{business:'Branded Indian-made foreign liquor producer with a portfolio spanning mass, premium and super-premium brands.',growth:'Premiumisation, brand investment and higher-value mix are the principal growth levers.',longevity:'Brand strength and distribution create durability, but excise policy, grain/ENA costs and discretionary demand remain material.',risks:'Regulatory changes, input-cost inflation, advertising restrictions and valuation compression.',catalyst:'Premium mix expansion and continued EBITDA/PAT growth.'},
KRYSTAL:{business:'Integrated facilities-management provider across healthcare, education, government, airports, rail/metro, staffing, security, catering and waste services.',growth:'Growth is contract-led and depends on new wins, renewal rates, geographic scale and execution.',longevity:'Recurring service contracts support visibility, but labour intensity and working-capital collection determine quality.',risks:'Low margins, receivable delays, wage inflation and contract concentration.',catalyst:'Large contract wins with stable margins and stronger cash conversion.'},
PROTEAN:{business:'Digital public-infrastructure and e-governance services provider operating in regulated, mission-critical citizen and financial-data ecosystems.',growth:'Growth depends on new government/digital mandates, adjacent platforms and monetisation of existing infrastructure.',longevity:'Regulatory credentials and embedded platforms are durable, but growth can be lumpy and policy-dependent.',risks:'Government concentration, tender timing, pricing pressure and technology/compliance risk.',catalyst:'New mandates and sustained revenue/PAT acceleration without margin dilution.'},
JUSTDIAL:{business:'Local-search and business-discovery marketplace monetising listings, paid campaigns and digital merchant services.',growth:'The main levers are paid-campaign penetration, traffic monetisation, SME digitisation and product engagement.',longevity:'The balance sheet is resilient, but long-term durability depends on defending user traffic and improving monetisation.',risks:'Competition from search/social platforms, weak merchant spending and CFO lagging reported profit.',catalyst:'Consistent revenue growth with CFO converging toward PAT.'},
DBOL:{business:'Integrated sugar, distillery, ethanol and power business exposed to agricultural and commodity cycles.',growth:'Growth is driven by capacity utilisation, ethanol policy, sugar realisations and co-product economics.',longevity:'The cycle can create upside, but high leverage and low returns reduce resilience through downcycles.',risks:'Cane availability, sugar/ethanol policy, commodity prices, leverage and working capital.',catalyst:'Debt reduction and sustained improvement in ROE/ROCE.'},
LUMAXTECH:{business:'Automotive-component supplier serving vehicle manufacturers and platform programmes.',growth:'Growth depends on vehicle volumes, content per vehicle, new programme wins and the shift toward higher-value electronics and systems.',longevity:'OEM relationships and engineering capability support durability, but customer concentration and auto cyclicality matter.',risks:'OEM concentration, raw-material pass-through, capex intensity, leverage and EV transition execution.',catalyst:'Order-book conversion, margin expansion and debt reduction.'},
SONACOMS:{business:'Global mobility-technology and precision-component supplier focused on engineered systems for automotive OEMs, including EV programmes.',growth:'Growth is linked to content per vehicle, global OEM wins and expansion of EV and precision-technology programmes.',longevity:'Mission-critical components and engineering capability create switching costs, but the valuation discounts substantial future execution.',risks:'High valuation, auto-cycle weakness, customer concentration and programme execution.',catalyst:'EV programme ramp-up and earnings growth that catches up with the multiple.'},
TARSONS:{business:'Life-science and laboratory consumables manufacturer serving research, diagnostics and related laboratory applications.',growth:'Growth depends on capacity utilisation, product introductions, exports and customer adoption.',longevity:'The sector has structural demand, but the current return profile requires proof of scale economics.',risks:'Low ROE/ROCE, high valuation, execution risk, competition and delayed capacity payback.',catalyst:'Material improvement in utilisation, margins and return ratios.'}
};
function n(m){const x=Number(m?.value);return Number.isFinite(x)?x:null}
function q(r){const roe=n(r.metrics.roe),roce=n(r.metrics.roce),de=n(r.metrics.debtEquity),pe=n(r.metrics.pe),cfo=n(r.metrics.cfo),pat=n(r.metrics.pat); const cash=cfo!==null&&pat!==null&&pat!==0?cfo/pat:null; const quality=roe===null?5:Math.max(0,Math.min(25,Math.round((roe/25)*15+(roce||0)/30*10))); const growth=r.quarterly.revenue==='NOT REPORTED'?5:15; const longevity=de!==null?Math.max(0,Math.min(25,25-Math.round(de*12))):10; const price=pe===null?10:pe<15?23:pe<30?18:pe<50?11:5; return {quality,growth,longevity,price,total:quality+growth+longevity+price,cashConversion:cash};}
let md='# WealthOS — Narrative Fundamental & QGLP Review\n\nAs-of 2026-10-07. Scores are analytical heuristics derived from the stored metrics; they are not forecasts or investment advice.\n\n'; const rows=[];
for(const r of base.rows){const s=story[r.symbol], score=q(r); let decision=r.conclusion; if(score.total>=70)decision='BUY / ACCUMULATE WITH VALUATION DISCIPLINE'; else if(score.total>=55)decision='WATCHLIST / BUY ONLY AFTER CONFIRMATION'; else decision='AVOID OR WAIT FOR A MATERIAL RESET'; rows.push({...r,story:s,qglp:score,decision}); md+=`## ${r.symbol}\n\n### Investment thesis\n${s.business} ${s.growth} ${s.longevity}\n\n### Fundamental interpretation\n${r.summary} The key analytical issue is whether the reported return profile and cash generation justify the current valuation.\n\n### QGLP scorecard\n- Quality: ${score.quality}/25 — based on reported ROE, ROCE and balance-sheet risk.\n- Growth: ${score.growth}/25 — based on observed revenue history; no unsupported forecast is assumed.\n- Longevity: ${score.longevity}/25 — based on leverage, business durability and execution risk.\n- Price: ${score.price}/25 — based on current PE and margin of safety.\n- Total: ${score.total}/100.\n\n### Risks\n${s.risks}\n\n### Catalysts\n${s.catalyst}\n\n### Decision\n**${decision}**\n\nWhy: ${r.why} The decision should be reconsidered if ${s.catalyst.toLowerCase()} or if the stated risks worsen.\n\nSource: ${r.source}\n\n---\n\n`;}
md+='## Portfolio-level conclusion\n\nThe strongest qualitative profiles are businesses with durable platforms or brands, but valuation discipline is essential. Low-return or highly leveraged names should not be treated as bargains merely because their PE is low. The report’s conclusions are research views based on public evidence and should be paired with the latest results and personal risk limits.\n'; const dir=path.join(root,'reports','fundamental-review'); fs.writeFileSync(path.join(dir,'NINE_STOCK_NARRATIVE_QGLP_2026-10-07.md'),md); fs.writeFileSync(path.join(dir,'NINE_STOCK_NARRATIVE_QGLP_2026-10-07.json'),JSON.stringify({generatedAt:new Date().toISOString(),rows},null,2)); console.log(JSON.stringify({rows:rows.length,output:'reports/fundamental-review/NINE_STOCK_NARRATIVE_QGLP_2026-10-07.md'},null,2));
