import fs from 'node:fs';
import path from 'node:path';
import Database from 'better-sqlite3';

const root = process.cwd();
const db = new Database(path.join(root, 'portfolio.db'), { readonly: true });
const outDir = path.join(root, 'outputs/fundamental_dossiers/pilot_25');
fs.mkdirSync(outDir, { recursive: true });
const fact = db.prepare(`SELECT value,periodEnd,periodType,provider,availableAt,fetchedAt FROM company_facts WHERE symbol=? AND metric=? AND value IS NOT NULL ORDER BY CASE WHEN availableAt IS NOT NULL THEN 0 ELSE 1 END, COALESCE(availableAt,fetchedAt) DESC, COALESCE(periodEnd,'') DESC LIMIT 1`);
function v(s, ms) { for (const m of ms) { const r=fact.get(s,m); if(r) return Number(r.value); } return null; }
const data = {};
for (const s of ['AZAD','RRKABEL']) data[s] = {
  revenue:v(s,['revenue']), op:v(s,['operating_profit']), pat:v(s,['pat']), cfo:v(s,['cfo']), capex:v(s,['capex_cash_outflow','capex']), de:v(s,['debt_to_equity_reported','debt_to_equity']), ic:v(s,['interest_coverage']), roe:v(s,['roe_pct','roe']), roce:v(s,['roce_reported']), pe:v(s,['pe_ttm','pe_ratio']), mcap:v(s,['market_cap_cr','market_cap']), promoter:v(s,['promoter_holding']), fii:v(s,['fii_holding']), dii:v(s,['dii_holding'])
};
function snapshotText(s, endpoint) { const r=db.prepare(`SELECT response_json FROM fundamental_endpoint_snapshots WHERE symbol=? AND provider='TRENDLYNE_MCP' AND endpoint=? ORDER BY fetched_at DESC LIMIT 1`).get(s,endpoint); try { const o=JSON.parse(r?.response_json||'{}'); return o?.content?.map(x=>x.text||'').join('\n')||''; } catch { return ''; } }
for (const s of ['AZAD','RRKABEL']) { const t=snapshotText(s,'overview'); data[s].rsi=t.match(/Relative Strength Index \| ([0-9.]+)/i)?.[1]??null; data[s].mfi=t.match(/Money Flow Index \| ([0-9.]+)/i)?.[1]??null; data[s].momentum=t.match(/Momentum Score.*?\n.*?m_value: ([0-9.]+)/is)?.[1]??null; }
const f = (x,u='') => x == null ? 'Not available in the verified local dataset' : `${x.toFixed(2)}${u}`;
const missing = (s, fields) => fields.filter(k => data[s][k] == null).map(k => k).join(', ') || 'None';
const rows = [
 ['1. Immediate market catalyst & sentiment',`Current provider snapshot shows momentum score ${data.AZAD.momentum??'not available'}, RSI ${data.AZAD.rsi??'not available'} and MFI ${data.AZAD.mfi??'not available'}. This indicates the present market setup, not a business catalyst; verified catalyst evidence is still required.`,`Current provider snapshot shows momentum score ${data.RRKABEL.momentum??'not available'}, RSI ${data.RRKABEL.rsi??'not available'} and MFI ${data.RRKABEL.mfi??'not available'}. This indicates the present market setup, not a business catalyst; verified catalyst evidence is still required.`],
 ['2. Core product utility','Business description is not present as a verified canonical fact.','Business description is not present as a verified canonical fact.'],
 ['3. Strengths & moat','Competitive moat evidence requires verified filings/company documents; not inferred from ratios.','Competitive moat evidence requires verified filings/company documents; not inferred from ratios.'],
 ['4. Customer concentration risk','Customer concentration is unavailable without verified annual-report disclosures.','Customer concentration is unavailable without verified annual-report disclosures.'],
 ['5. Supplier concentration & pricing power','Supplier/pricing evidence is unavailable without verified filings or documents.','Supplier/pricing evidence is unavailable without verified filings or documents.'],
 ['6. Total addressable market','TAM is not a canonical financial fact and is not available in the local evidence set.','TAM is not a canonical financial fact and is not available in the local evidence set.'],
 ['7. Reinvestment runway',`Capex ${f(data.AZAD.capex,' Cr')}; runway narrative unavailable without verified guidance/order-book evidence.`,`Capex ${f(data.RRKABEL.capex,' Cr')}; runway narrative unavailable without verified guidance/order-book evidence.`],
 ['8. Capital allocation efficiency',`ROCE ${f(data.AZAD.roce,'%')}; debt/equity ${f(data.AZAD.de)}; interpretation requires dated trend history.`,`ROCE ${f(data.RRKABEL.roce,'%')}; debt/equity ${f(data.RRKABEL.de)}; interpretation requires dated trend history.`],
 ['9. Revenue quality & segment dynamics','Segment mix and contract quality unavailable from verified canonical facts.','Segment mix and contract quality unavailable from verified canonical facts.'],
 ['10. Margin trajectory',`Operating profit ${f(data.AZAD.op,' Cr')} on revenue ${f(data.AZAD.revenue,' Cr')}; dated margin trend not yet complete.`,`Operating profit ${f(data.RRKABEL.op,' Cr')} on revenue ${f(data.RRKABEL.revenue,' Cr')}; dated margin trend not yet complete.`],
 ['11. Cash flow vs PAT integrity',`CFO ${f(data.AZAD.cfo,' Cr')} versus PAT ${f(data.AZAD.pat,' Cr')} indicates weak current cash conversion; capex is ${f(data.AZAD.capex,' Cr')}. This requires working-capital and execution monitoring.`,`CFO ${f(data.RRKABEL.cfo,' Cr')} versus PAT ${f(data.RRKABEL.pat,' Cr')} indicates positive current cash conversion; capex is ${f(data.RRKABEL.capex,' Cr')}. The conclusion remains subject to a dated multi-year trend.`],
 ['12. Balance sheet quality & leverage',`Debt/equity ${f(data.AZAD.de)}; interest coverage ${f(data.AZAD.ic,'x')}.`,`Debt/equity ${f(data.RRKABEL.de)}; interest coverage ${f(data.RRKABEL.ic,'x')}.`],
 ['13. Governance, promoters & audits',`Promoter holding ${f(data.AZAD.promoter,'%')}; governance/audit evidence unavailable.`,`Promoter holding ${f(data.RRKABEL.promoter,'%')}; governance/audit evidence unavailable.`],
 ['14. Key structural risks','Risk disclosures require verified company documents; no unsupported risk claims are made.','Risk disclosures require verified company documents; no unsupported risk claims are made.'],
 ['15. Valuation & market benchmarking',`Market cap ${f(data.AZAD.mcap,' Cr')}; P/E ${f(data.AZAD.pe)}. The valuation is only a starting point because canonical sources contain conflicting values and no peer-normalised benchmark.`,`Market cap ${f(data.RRKABEL.mcap,' Cr')}; P/E ${f(data.RRKABEL.pe)}. The valuation is only a starting point because no peer-normalised benchmark is persisted.`]
];
const intro = '# Institutional Investment Due-Diligence Assessment\n\nThis report follows the requested 15-phase framework. Quantitative statements use persisted canonical facts; qualitative statements are explicitly marked unavailable when verified evidence is absent. No provider-label guessing, extrapolation or LLM inference is used.\n\n';
const md = [intro, '| Phase & topic | Azad Engineering (NSE: AZAD) | R R Kabel (NSE: RRKABEL) |', '|---|---|---|', ...rows.map(r=>`| **${r[0]}** | ${r[1]} | ${r[2]} |`), '', '## Quantitative evidence summary', '', `| Metric | AZAD | RRKABEL |`, '|---|---:|---:|', ...[['Revenue (Cr)','revenue'],['Operating profit (Cr)','op'],['PAT (Cr)','pat'],['CFO (Cr)','cfo'],['Capex (Cr)','capex'],['Debt/equity','de'],['Interest coverage','ic'],['ROE (%)','roe'],['ROCE (%)','roce'],['P/E','pe'],['Market cap (Cr)','mcap'],['Promoter holding (%)','promoter'],['FII holding (%)','fii'],['DII holding (%)','dii']].map(([n,k])=>`| ${n} | ${f(data.AZAD[k])} | ${f(data.RRKABEL[k])} |`), '', '## Data gaps requiring acquisition', `AZAD: ${missing('AZAD',['revenue','op','pat','cfo','capex','de','ic','roe','roce','pe','mcap','promoter','fii','dii'])}.`, `RRKABEL: ${missing('RRKABEL',['revenue','op','pat','cfo','capex','de','ic','roe','roce','pe','mcap','promoter','fii','dii'])}.`, '', 'A complete institutional narrative requires verified company descriptions, catalysts, customer/supplier concentration, TAM, segment mix, order-book/guidance, governance/audit disclosures, risk disclosures and peer benchmarks. These are not filled from unsupported assumptions.'];
const reportPath = path.join(outDir,'Institutional_Due_Diligence_AZAD_RRKABEL.md');
fs.writeFileSync(reportPath, md.join('\n')); db.close(); console.log(reportPath);
