export type WealthOSFieldSpec = {
  canonicalMetric: string;
  displayName: string;
  category:
    | 'IDENTITY'
    | 'VALUATION'
    | 'GROWTH'
    | 'PROFITABILITY'
    | 'CASH_FLOW'
    | 'BALANCE_SHEET'
    | 'OWNERSHIP'
    | 'GOVERNANCE'
    | 'SECTOR'
    | 'TECHNICAL'
    | 'QGLP'
    | 'RISK'
    | 'QUALITATIVE';

  requiredFor: Array<
    | 'BASIC_FUNDAMENTAL'
    | 'FULL_FUNDAMENTAL'
    | 'QGLP'
    | 'DCF'
    | 'DOSSIER'
    | 'STOCKSCAN'
    | 'RISK_MANAGEMENT'
  >;

  primarySource: 'FERE_NSE_XBRL' | 'TRENDLYNE_MCP' | 'KITE' | 'UPSTOX' | 'NSE' | 'BSE' | 'APP_DB';
  fallbackSources: string[];

  periodRequirement: 'LATEST' | 'DATED_QUARTERLY' | 'DATED_ANNUAL' | 'OHLCV_DAILY';
  freshnessDays: number;

  canBeDerived: boolean;
  derivationInputs?: string[];
  derivationFormula?: string;

  missingBehavior: 'BLOCK' | 'PARTIAL' | 'OPTIONAL';
};

export const WealthOSMasterFieldCatalog: WealthOSFieldSpec[] = [
  // ==========================================
  // IDENTITY & SECTOR
  // ==========================================
  {
    canonicalMetric: 'sector',
    displayName: 'Sector / Industry',
    category: 'SECTOR',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'APP_DB',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'LATEST',
    freshnessDays: 30,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'business_description',
    displayName: 'Business Description',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },

  // ==========================================
  // VALUATION
  // ==========================================
  {
    canonicalMetric: 'current_price',
    displayName: 'Current Price',
    category: 'VALUATION',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DCF', 'DOSSIER', 'STOCKSCAN'],
    primarySource: 'KITE',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'BLOCK',
  },
  {
    canonicalMetric: 'market_cap',
    displayName: 'Market Cap',
    category: 'VALUATION',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER', 'STOCKSCAN'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'BLOCK',
  },
  {
    canonicalMetric: 'pe',
    displayName: 'P/E Ratio',
    category: 'VALUATION',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER', 'STOCKSCAN'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'pb',
    displayName: 'P/B Ratio',
    category: 'VALUATION',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER', 'STOCKSCAN'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'ev_ebitda',
    displayName: 'EV / EBITDA',
    category: 'VALUATION',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'peg',
    displayName: 'PEG Ratio',
    category: 'VALUATION',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },

  // ==========================================
  // PROFITABILITY & RETURNS
  // ==========================================
  {
    canonicalMetric: 'roe',
    displayName: 'Return on Equity (ROE)',
    category: 'PROFITABILITY',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER', 'STOCKSCAN'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'roce',
    displayName: 'Return on Capital Employed (ROCE)',
    category: 'PROFITABILITY',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER', 'STOCKSCAN'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: true, // Can be derived if needed, but often fetched
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'roic',
    displayName: 'Return on Invested Capital (ROIC)',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'roa',
    displayName: 'Return on Assets (ROA)',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'operating_margin',
    displayName: 'Operating Margin',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'APP_DB', // derived
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: true,
    derivationInputs: ['operating_profit', 'revenue'],
    derivationFormula: 'operating_profit / revenue',
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'pat_margin',
    displayName: 'PAT Margin',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'APP_DB',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: true,
    derivationInputs: ['pat', 'revenue'],
    derivationFormula: 'pat / revenue',
    missingBehavior: 'PARTIAL',
  },
  
  // ==========================================
  // INCOME STATEMENT
  // ==========================================
  {
    canonicalMetric: 'revenue',
    displayName: 'Revenue',
    category: 'GROWTH',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_QUARTERLY',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'BLOCK',
  },
  {
    canonicalMetric: 'operating_profit',
    displayName: 'Operating Profit',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP', // often from TL, or derived
    fallbackSources: [],
    periodRequirement: 'DATED_QUARTERLY',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'pat',
    displayName: 'Profit After Tax (PAT)',
    category: 'PROFITABILITY',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_QUARTERLY',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'BLOCK',
  },
  {
    canonicalMetric: 'eps',
    displayName: 'Earnings Per Share (EPS)',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_QUARTERLY',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'finance_costs',
    displayName: 'Finance Costs',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_QUARTERLY',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'depreciation',
    displayName: 'Depreciation',
    category: 'PROFITABILITY',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_QUARTERLY',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },

  // ==========================================
  // CASH FLOW
  // ==========================================
  {
    canonicalMetric: 'cfo',
    displayName: 'Cash Flow from Operations (CFO)',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DCF', 'DOSSIER'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'cfi',
    displayName: 'Cash Flow from Investing (CFI)',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'cff',
    displayName: 'Cash Flow from Financing (CFF)',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'capex_cash_outflow',
    displayName: 'Capital Expenditure',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DCF', 'DOSSIER'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['TRENDLYNE_MCP'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'fcf',
    displayName: 'Free Cash Flow (FCF)',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DCF', 'DOSSIER'],
    primarySource: 'APP_DB',
    fallbackSources: [],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: true,
    derivationInputs: ['cfo', 'capex_cash_outflow'],
    derivationFormula: 'cfo - Math.abs(capex_cash_outflow)',
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'fcf_margin',
    displayName: 'FCF Margin',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'APP_DB',
    fallbackSources: [],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: true,
    derivationInputs: ['fcf', 'revenue'],
    derivationFormula: 'fcf / revenue',
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'fcf_pat_ratio',
    displayName: 'FCF / PAT Ratio',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'APP_DB',
    fallbackSources: [],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: true,
    derivationInputs: ['fcf', 'pat'],
    derivationFormula: 'fcf / pat',
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'cfo_pat_ratio',
    displayName: 'CFO / PAT Ratio',
    category: 'CASH_FLOW',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER'],
    primarySource: 'APP_DB',
    fallbackSources: [],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: true,
    derivationInputs: ['cfo', 'pat'],
    derivationFormula: 'cfo / pat',
    missingBehavior: 'PARTIAL',
  },

  // ==========================================
  // BALANCE SHEET & DEBT
  // ==========================================
  {
    canonicalMetric: 'debt_to_equity',
    displayName: 'Debt to Equity',
    category: 'BALANCE_SHEET',
    requiredFor: ['BASIC_FUNDAMENTAL', 'FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER', 'RISK_MANAGEMENT'],
    primarySource: 'TRENDLYNE_MCP', // sometimes XBRL
    fallbackSources: ['FERE_NSE_XBRL'],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'net_debt',
    displayName: 'Net Debt',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER', 'DCF'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'borrowings',
    displayName: 'Borrowings',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: ['FERE_NSE_XBRL'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'current_ratio',
    displayName: 'Current Ratio',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'dscr',
    displayName: 'Debt Service Coverage Ratio (DSCR)',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'FERE_NSE_XBRL',
    fallbackSources: ['APP_DB'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: true,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'interest_coverage',
    displayName: 'Interest Coverage Ratio',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'APP_DB',
    fallbackSources: [],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: true,
    derivationInputs: ['operating_profit', 'finance_costs'],
    derivationFormula: 'operating_profit / finance_costs',
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'working_capital',
    displayName: 'Working Capital',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DCF'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'inventories',
    displayName: 'Inventories',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: ['FERE_NSE_XBRL'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'receivables',
    displayName: 'Receivables',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: ['FERE_NSE_XBRL'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'cwip',
    displayName: 'Capital Work in Progress',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: ['FERE_NSE_XBRL'],
    periodRequirement: 'DATED_ANNUAL',
    freshnessDays: 180,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'book_value',
    displayName: 'Book Value',
    category: 'BALANCE_SHEET',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },

  // ==========================================
  // OWNERSHIP & GOVERNANCE
  // ==========================================
  {
    canonicalMetric: 'promoter_holding',
    displayName: 'Promoter Holding',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'promoter_pledge',
    displayName: 'Promoter Pledge',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'DOSSIER', 'RISK_MANAGEMENT'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'fii_holding',
    displayName: 'FII Holding',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'fii_change',
    displayName: 'FII Change',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'dii_holding',
    displayName: 'DII / MF Holding',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'public_holding',
    displayName: 'Public Holding',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'insider_trades',
    displayName: 'Insider Trades',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'bulk_block_deals',
    displayName: 'Bulk / Block Deals',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'sast_disclosures',
    displayName: 'SAST Disclosures',
    category: 'OWNERSHIP',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },

  // ==========================================
  // QUALITATIVE & EVENTS
  // ==========================================
  {
    canonicalMetric: 'corporate_actions',
    displayName: 'Corporate Actions',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'management_changes',
    displayName: 'Management Changes',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'investor_presentations',
    displayName: 'Investor Presentations',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'annual_reports',
    displayName: 'Annual Reports',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'credit_debt_events',
    displayName: 'Credit / Debt Events',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'RISK_MANAGEMENT'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'contingent_liabilities',
    displayName: 'Contingent Liabilities',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP', 'RISK_MANAGEMENT'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'order_book',
    displayName: 'Order Book',
    category: 'QUALITATIVE',
    requiredFor: ['FULL_FUNDAMENTAL', 'QGLP'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 90,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },

  // ==========================================
  // TECHNICAL / MARKET
  // ==========================================
  {
    canonicalMetric: 'stock_ohlcv',
    displayName: 'Stock OHLCV',
    category: 'TECHNICAL',
    requiredFor: ['DOSSIER', 'STOCKSCAN'],
    primarySource: 'KITE',
    fallbackSources: ['UPSTOX'],
    periodRequirement: 'OHLCV_DAILY',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'sector_index_ohlcv',
    displayName: 'Sector Index OHLCV',
    category: 'TECHNICAL',
    requiredFor: ['DOSSIER', 'STOCKSCAN'],
    primarySource: 'KITE',
    fallbackSources: ['UPSTOX'],
    periodRequirement: 'OHLCV_DAILY',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'volume',
    displayName: 'Volume',
    category: 'TECHNICAL',
    requiredFor: ['DOSSIER', 'STOCKSCAN'],
    primarySource: 'KITE',
    fallbackSources: ['UPSTOX'],
    periodRequirement: 'OHLCV_DAILY',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'PARTIAL',
  },
  {
    canonicalMetric: 'delivery_average',
    displayName: 'Delivery Average',
    category: 'TECHNICAL',
    requiredFor: ['DOSSIER', 'STOCKSCAN'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  },
  {
    canonicalMetric: 'piotroski_score',
    displayName: 'Piotroski Score',
    category: 'TECHNICAL', // or QUALITY
    requiredFor: ['FULL_FUNDAMENTAL', 'DOSSIER'],
    primarySource: 'TRENDLYNE_MCP',
    fallbackSources: [],
    periodRequirement: 'LATEST',
    freshnessDays: 1,
    canBeDerived: false,
    missingBehavior: 'OPTIONAL',
  }
];
