import type { Fact, PeriodType, RawXbrlFact } from '../domain/types.js';
import { canonicalMetric, metricDefinition } from './metricDefinitions.js';
import { convertUnit, flagMagnitudeSuspect } from './units.js';
const quarterFor=(d:string)=>{const m=Number(d.slice(5,7));return m===6?1:m===9?2:m===12?3:m===3?4:0;};
const fyFor=(d:string)=>Number(d.slice(5,7))>=4?Number(d.slice(0,4)):Number(d.slice(0,4))-1;
const fyStart=(d:string)=>`${fyFor(d)}-04-01`;
const ytdType=(d:string):PeriodType=>({1:'YTD_3M',2:'YTD_6M',3:'YTD_9M',4:'YTD_12M'} as any)[quarterFor(d)]||'YTD_12M';
export function classifyPeriod(raw:RawXbrlFact):PeriodType { const def=metricDefinition(raw.metric); if(!def) throw new Error(`METRIC_UNMAPPED:${raw.metric}`); if(def.periodBasis==='POINT_IN_TIME') return 'POINT_IN_TIME'; if(raw.contextRef==='OneD') return 'DISCRETE_Q'; if(raw.contextRef==='FourD') return ytdType(raw.periodEnd); throw new Error(`XBRL_CONTEXT_UNSUPPORTED:${raw.contextRef}`); }
const id=(r:RawXbrlFact,p:PeriodType,v:number)=>`${r.isin}|${r.scope}|${canonicalMetric(r.metric)}|${p}|${r.periodEnd}|${r.vintage||1}|${v}`;
function makeFact(r:RawXbrlFact,p:PeriodType,v:number,flags:string[]=[],derivation?:Fact['derivation'],vintage?:number):Fact { const c=convertUnit(v,r.unit,Boolean(r.source?.toUpperCase().includes('TRENDLYNE'))); return {factId:id(r,p,v),isin:r.isin,symbol:r.symbol,scope:r.scope,metric:canonicalMetric(r.metric),periodType:p,periodStart:p==='POINT_IN_TIME'?r.periodEnd:p==='DISCRETE_Q'?r.periodStart:fyStart(r.periodEnd),periodEnd:r.periodEnd,valueCr:c.value,unit:c.unit,sourceTier:r.sourceTier||'STATUTORY',source:r.source,sourceRef:r.sourceRef,availableAt:r.availableAt,vintage:vintage||r.vintage||1,derivation,qualityFlags:[...flags,...(c.derivation?['UNIT_CONVERTED']:[])],quarantined:false}; }
export function normalizeXbrlFacts(rows:RawXbrlFact[]):Fact[] { const latest=new Map<string,Fact>(); const rawPrevious=new Map<string,number>(); for(const r of [...rows].sort((a,b)=>a.periodEnd.localeCompare(b.periodEnd)||a.availableAt.localeCompare(b.availableAt))){const p=classifyPeriod(r),k=`${r.isin}|${r.scope}|${canonicalMetric(r.metric)}|${p}|${r.periodEnd}`,prior=latest.get(k),flags:string[]=[]; if(prior&&prior.valueCr!==null&&flagMagnitudeSuspect(r.value,rawPrevious.get(k) ?? null))flags.push('UNIT_SUSPECT'); const f=makeFact(r,p,r.value,flags.concat(prior&&prior.value!==r.value?['RESTATED']:[]),undefined,prior?prior.vintage+1:r.vintage); if(prior)f.supersedesId=prior.factId; latest.set(k,f); rawPrevious.set(k,r.value);} return deriveMissingQuarters([...latest.values()]); }
function deriveMissingQuarters(facts:Fact[]):Fact[]{const out=[...facts];for(const y of facts.filter(f=>f.periodType==='YTD_6M'||f.periodType==='YTD_9M')){const q=quarterFor(y.periodEnd),prevEnd=q===2?`${fyFor(y.periodEnd)}-06-30`:`${fyFor(y.periodEnd)}-09-30`,prev=facts.find(f=>f.periodEnd===prevEnd&&f.periodType!=='POINT_IN_TIME');if(prev&&!facts.some(f=>f.periodEnd===y.periodEnd&&f.periodType==='DISCRETE_Q'))out.push({...y,periodType:'DISCRETE_Q',periodStart:prevEnd,valueCr:(y.valueCr||0)-(prev.valueCr||0),derivation:{formula:'YTD current − YTD previous',inputs:[prev.factId,y.factId]},qualityFlags:[...y.qualityFlags,'DERIVED'],factId:`${y.factId}|derived`});}for(const annual of facts.filter(f=>f.periodType==='YTD_12M'&&quarterFor(f.periodEnd)===4)){const y9=facts.find(f=>f.periodType==='YTD_9M'&&fyFor(f.periodEnd)===fyFor(annual.periodEnd));if(y9&&!facts.some(f=>f.periodType==='DISCRETE_Q'&&quarterFor(f.periodEnd)===4))out.push({...annual,periodType:'DISCRETE_Q',valueCr:(annual.valueCr||0)-(y9.valueCr||0),derivation:{formula:'Annual − YTD_9M',inputs:[annual.factId,y9.factId]},qualityFlags:[...annual.qualityFlags,'DERIVED'],factId:`${annual.factId}|derived`});}return out;}
export function reconcileDiscreteFacts(facts:Fact[],a=0.05,r=0.001):Fact[]{const out=facts.map(f=>({...f,qualityFlags:[...f.qualityFlags]}));const groups=new Map<string,Fact[]>();for(const f of out){const k=`${f.isin}|${f.scope}|${f.metric}|${fyFor(f.periodEnd)}`;groups.set(k,[...(groups.get(k)||[]),f]);}for(const g of groups.values()){const qs=g.filter(f=>f.periodType==='DISCRETE_Q'&&!f.qualityFlags.includes('DERIVED')),annual=g.find(f=>f.periodType==='YTD_12M'&&quarterFor(f.periodEnd)===4),mark=(xs:Fact[],flag:string)=>xs.forEach(f=>{if(!f.qualityFlags.includes(flag))f.qualityFlags.push(flag);});if(!annual||qs.length!==4){mark(g,'RECON_UNVERIFIED');continue;}if(Math.abs(qs.reduce((s,f)=>s+(f.valueCr||0),0)-(annual.valueCr||0))>Math.max(a,Math.abs(annual.valueCr||0)*r))mark([...qs,annual],'PERIOD_RECON_FAIL');const y6=g.find(f=>f.periodType==='YTD_6M'),q1=g.find(f=>f.periodType==='DISCRETE_Q'&&quarterFor(f.periodEnd)===1),q2=g.find(f=>f.periodType==='DISCRETE_Q'&&quarterFor(f.periodEnd)===2);if(y6&&q1&&q2&&Math.abs((q1.valueCr||0)+(q2.valueCr||0)-(y6.valueCr||0))>Math.max(a,Math.abs(y6.valueCr||0)*r))mark([y6,q1,q2],'PERIOD_RECON_FAIL');for(const y of g.filter(f=>f.periodType.startsWith('YTD_'))){const q=g.find(f=>f.periodType==='DISCRETE_Q'&&f.periodEnd===y.periodEnd);if(q&&q.valueCr!==null&&y.valueCr!==null&&q.valueCr>y.valueCr+Math.max(a,Math.abs(y.valueCr)*r))mark([q,y],'PERIOD_RECON_FAIL');}}return out;}
