import express, { Request, Response } from 'express';
import { getServerConfig } from '../config.js';
import { authenticateFamily, roleAllows } from '../auth/familyRoleAuth.js';
import { dbAll, dbGet, dbRun, getDB } from '../database.js';
const router=express.Router();
function principal(req:Request,res:Response,required:'viewer'|'admin'='viewer'){const p=authenticateFamily(req.headers as any,getServerConfig().APP_PASSWORD);if(!p||!roleAllows(p,required)){res.status(p?403:401).json({success:false,error:p?'ROLE_FORBIDDEN':'UNAUTHORIZED'});return null;}return p;}
router.get('/connections',(req,res)=>{if(!principal(req,res))return;dbAll(getDB(),'SELECT id,provider,account_label,portfolio,status,credential_ref,created_by,created_at,updated_at FROM broker_connections ORDER BY id DESC').then(data=>res.json({success:true,data})).catch(()=>res.status(500).json({success:false,error:'BROKER_CONNECTION_READ_FAILED'}));});
router.post('/connections',async(req,res)=>{const p=principal(req,res,'admin');if(!p)return;const b=req.body||{},provider=String(b.provider||'').toUpperCase();if(!['ZERODHA','IBKR','IIFL','CAMS','MANUAL'].includes(provider)||!String(b.account_label||'').trim()||!String(b.portfolio||'').trim())return res.status(400).json({success:false,error:'INVALID_BROKER_CONNECTION'});try{const r:any=await dbRun(getDB(),'INSERT INTO broker_connections(provider,account_label,portfolio,credential_ref,created_by) VALUES (?,?,?,?,?) ON CONFLICT(provider,account_label,portfolio) DO UPDATE SET status=\'ACTIVE\',credential_ref=COALESCE(excluded.credential_ref,broker_connections.credential_ref),updated_at=CURRENT_TIMESTAMP',[provider,String(b.account_label).trim(),String(b.portfolio).trim(),b.credential_ref?String(b.credential_ref).trim():null,p.userId]);res.status(201).json({success:true,id:r.lastID||null});}catch{res.status(409).json({success:false,error:'BROKER_CONNECTION_CONFLICT'});}});
router.get('/import-jobs/:id',(req,res)=>{if(!principal(req,res))return;dbGet(getDB(),'SELECT * FROM broker_import_jobs WHERE id=?',[Number(req.params.id)]).then(row=>row?res.json({success:true,data:row}):res.status(404).json({success:false,error:'IMPORT_JOB_NOT_FOUND'})).catch(()=>res.status(500).json({success:false,error:'IMPORT_JOB_READ_FAILED'}));});
router.post('/connections/:id/import-jobs',async(req,res)=>{const p=principal(req,res,'admin');if(!p)return;const key=String(req.headers['idempotency-key']||'').trim(),b=req.body||{};if(!key||key.length>200)return res.status(400).json({success:false,error:'IDEMPOTENCY_KEY_REQUIRED'});if(!['STATEMENT','API_SYNC','MANUAL_FILE'].includes(String(b.source_kind||'').toUpperCase()))return res.status(400).json({success:false,error:'INVALID_SOURCE_KIND'});const db=getDB(),c=await dbGet<any>(db,'SELECT id,status FROM broker_connections WHERE id=?',[Number(req.params.id)]);if(!c)return res.status(404).json({success:false,error:'BROKER_CONNECTION_NOT_FOUND'});if(c.status!=='ACTIVE')return res.status(409).json({success:false,error:'BROKER_CONNECTION_NOT_ACTIVE'});const old=await dbGet<any>(db,'SELECT * FROM broker_import_jobs WHERE connection_id=? AND idempotency_key=?',[c.id,key]);if(old)return res.status(200).json({success:true,replayed:true,data:old});try{const r:any=await dbRun(db,'INSERT INTO broker_import_jobs(connection_id,idempotency_key,source_kind,requested_from,requested_to,created_by) VALUES (?,?,?,?,?,?)',[c.id,key,String(b.source_kind).toUpperCase(),b.requested_from||null,b.requested_to||null,p.userId]);res.status(202).json({success:true,data:await dbGet(db,'SELECT * FROM broker_import_jobs WHERE id=?',[r.lastID])});}catch{res.status(409).json({success:false,error:'IMPORT_JOB_DUPLICATE'});}});
export default router;

