import express, { Request } from 'express';
import { getServerConfig, timingSafeMatch } from '../config.js';
import { dbAll, dbGet, dbRun, getDB } from '../database.js';
const router=express.Router();
const auth=(write=false)=>(req:Request,res:any,next:any)=>{const cfg=getServerConfig();if(cfg.APP_PASSWORD&&!timingSafeMatch(String(req.headers['x-app-password']||''),cfg.APP_PASSWORD))return res.status(401).json({success:false,error:'UNAUTHORIZED'});if(write&&!['owner','admin','editor'].includes(String(req.headers['x-family-role']||'owner').toLowerCase()))return res.status(403).json({success:false,error:'ROLE_FORBIDDEN'});(req as any).actor=String(req.headers['x-family-user']||'owner');next()};
const iso=(v:any)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00Z'));
const validChecklist=(v:any)=>Array.isArray(v)&&v.every(x=>x&&typeof x.key==='string'&&typeof x.status==='string');
router.get('/review-reminders',auth(),async(req,res)=>{const p=String(req.query.portfolio||'').trim();if(!p)return res.status(400).json({success:false,error:'PORTFOLIO_REQUIRED'});const data=await dbAll(getDB(),`SELECT *,CASE WHEN status IN ('COMPLETED','DISMISSED') THEN status WHEN due_on<date('now') THEN 'OVERDUE' WHEN due_on<=date('now','+30 day') THEN 'DUE_SOON' ELSE 'OPEN' END due_status FROM nri_review_reminders WHERE portfolio=? ORDER BY due_on,id`,[p]);res.json({success:true,data})});
router.post('/review-reminders',auth(true),async(req,res)=>{const b=req.body||{};if(!b.portfolio||!b.reminder_type||!iso(b.due_on))return res.status(400).json({success:false,error:'INVALID_REVIEW_REMINDER'});const r:any=await dbRun(getDB(),'INSERT INTO nri_review_reminders(portfolio,tracker_id,reminder_type,due_on,status,notes,created_by) VALUES(?,?,?,?,?,?,?)',[b.portfolio,b.tracker_id||null,b.reminder_type,b.due_on,b.status||'OPEN',b.notes||null,(req as any).actor]);res.status(201).json({success:true,id:r.lastID})});
router.patch('/review-reminders/:id',auth(true),async(req,res)=>{const id=Number(req.params.id),old:any=await dbGet(getDB(),'SELECT * FROM nri_review_reminders WHERE id=?',[id]);if(!old)return res.status(404).json({success:false,error:'NOT_FOUND'});const b=req.body||{};if(b.due_on&&!iso(b.due_on))return res.status(400).json({success:false,error:'INVALID_DATE'});const f=['due_on','status','notes'];await dbRun(getDB(),`UPDATE nri_review_reminders SET ${f.map(x=>x+'=?').join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`,[...f.map(x=>b[x]===undefined?old[x]:b[x]),id]);res.json({success:true})});
router.get('/repatriation-workflows',auth(),async(req,res)=>{const p=String(req.query.portfolio||'').trim();if(!p)return res.status(400).json({success:false,error:'PORTFOLIO_REQUIRED'});const rows=await dbAll(getDB(),'SELECT * FROM nri_repatriation_workflow WHERE portfolio=? ORDER BY requested_on DESC,id DESC',[p]);res.json({success:true,data:rows.map((r:any)=>({...r,checklist:JSON.parse(r.checklist_json||'[]')}))})});
router.post('/repatriation-workflows',auth(true),async(req,res)=>{const b=req.body||{};if(!b.portfolio||!iso(b.requested_on)||(b.target_on&&!iso(b.target_on))||(b.review_due_on&&!iso(b.review_due_on))||!validChecklist(b.checklist))return res.status(400).json({success:false,error:'INVALID_REPATRIATION_WORKFLOW'});const r:any=await dbRun(getDB(),'INSERT INTO nri_repatriation_workflow(portfolio,transfer_reference,source_account,destination_country,requested_on,target_on,review_due_on,checklist_json,status,advisor_reference,evidence_reference,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[b.portfolio,b.transfer_reference||null,b.source_account||null,b.destination_country||null,b.requested_on,b.target_on||null,b.review_due_on||null,JSON.stringify(b.checklist),b.status||'OPEN',b.advisor_reference||null,b.evidence_reference||null,b.notes||null,(req as any).actor]);res.status(201).json({success:true,id:r.lastID})});
router.patch('/repatriation-workflows/:id',auth(true),async(req,res)=>{const id=Number(req.params.id),old:any=await dbGet(getDB(),'SELECT * FROM nri_repatriation_workflow WHERE id=?',[id]);if(!old)return res.status(404).json({success:false,error:'NOT_FOUND'});const b=req.body||{};if(b.checklist!==undefined&&!validChecklist(b.checklist))return res.status(400).json({success:false,error:'INVALID_CHECKLIST'});const f=['target_on','review_due_on','checklist_json','status','advisor_reference','evidence_reference','notes'];await dbRun(getDB(),`UPDATE nri_repatriation_workflow SET ${f.map(x=>x+'=?').join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`,[...f.map(x=>x==='checklist_json'?(b.checklist===undefined?old[x]:JSON.stringify(b.checklist)):(b[x]===undefined?old[x]:b[x])),id]);res.json({success:true})});
export default router;

